### ISSUE TITLE
Add Reporting

### ISSUE THREAD

**Issue by isaiahnields** [snl-dev-team/snl-inventory-app#53]
- [x] Download button on product and order cards

- [x] Write script to parse .json into well formatted csv

**Comment by zeroxjackson** [comment]
@isaiahnields https://www.tutsandtips.com/javascript/how-to-download-a-text-file-with-javascript/

**Comment by isaiahnields** [comment]
Just added download buttons, but they only download the json rather than CSV. Will work on this later today.

**Comment by zeroxjackson** [comment]
Looks like we may need to change CORS settings. I get an error when I click download button.

<img width="566" alt="Screen Shot 2020-12-06 at 3 37 59 PM" src="https://user-images.githubusercontent.com/57923799/101291740-066a6900-37d9-11eb-9424-9bb667c143f1.png">

**Comment by isaiahnields** [comment]
Oh good catch. We need to pass in the JWT when we request the download.

**Comment by isaiahnields** [comment]
Should be fixed now.

**Comment by zeroxjackson** [comment]
working 👍🏼

**Comment by zeroxjackson** [comment]
@isaiahnields actually... yes it is working when i run master locally, but when I visit the deployed link now CORS is blocking all requests, so there is no data at all

**Comment by isaiahnields** [comment]
[Order T3JkZXI6MjI= Report (2).xlsx](https://github.com/snl-dev-team/snl-inventory-app/files/5679677/Order.T3JkZXI6MjI.Report.2.xlsx)

Here's an example of the new export.

**Comment by zeroxjackson** [comment]
Looks really cool!
