### ISSUE TITLE
SQL String Bug

### ISSUE THREAD

**Issue by zeroxjackson** [snl-dev-team/snl-inventory-app#54]
You cannot name a product with an ' character. (Obviously a very low importance bug).

**Comment by isaiahnields** [comment]
Looks like we can prevent this issues by doubling quotes in our strings. See https://stackoverflow.com/questions/1586560/how-do-i-escape-a-single-quote-in-sql-server.

@lnields want to take care of this?

**Comment by isaiahnields** [comment]
migration to graphql fixed
