### ISSUE TITLE
Orders Page Bug

### ISSUE THREAD

**Issue by zeroxjackson** [snl-dev-team/snl-inventory-app#55]
On the deployed app (https://master.d11lgpk9h845n4.amplifyapp.com/orders) no items are populating the orders page.

**Comment by isaiahnields** [comment]
![Screen Shot 2020-11-19 at 7 40 26 PM](https://user-images.githubusercontent.com/12752162/99741426-1c6cef80-2a9f-11eb-8d48-7c99cae5b43f.png)

It seems to be working for me.
