### ISSUE TITLE
Redesign Create Item Forms

### ISSUE THREAD

**Issue by zeroxjackson** [snl-dev-team/snl-inventory-app#85]
- [x] Currency formatting

- [x] Notes field updates
  - Return key for new lines
  - Place at bottom

- [x] Reorganize fields
  - Unit type adjacent to count
  - Other improvements

**Comment by zeroxjackson** [comment]
So there is a bug in the material ui select that makes it misaligned in the form. Only solution currently is just to add extra margin manually, but when this gets fixed it will look fucky.

<img width="598" alt="Screen Shot 2020-12-05 at 10 49 12 PM" src="https://user-images.githubusercontent.com/57923799/101270966-72eb5680-374c-11eb-92ec-0660a91b25c6.png">

https://github.com/mui-org/material-ui/issues/18394

**Comment by isaiahnields** [comment]
Just fixed all issues.
![Screen Shot 2020-12-05 at 11 06 57 PM](https://user-images.githubusercontent.com/12752162/101271193-a7f8a880-374e-11eb-94ea-af31a8189b99.png)
![Screen Shot 2020-12-05 at 11 07 04 PM](https://user-images.githubusercontent.com/12752162/101271198-afb84d00-374e-11eb-99d8-2f648e578fe8.png)

![Screen Shot 2020-12-05 at 11 07 08 PM](https://user-images.githubusercontent.com/12752162/101271195-ab8c2f80-374e-11eb-8252-769134988890.png)

![Screen Shot 2020-12-05 at 11 07 01 PM](https://user-images.githubusercontent.com/12752162/101271202-b5159780-374e-11eb-8827-6d5efafd9c15.png)

**Comment by isaiahnields** [comment]
These could probably use more tuning (e.g. the completed checkmark looks kinda shitty next to notes), but this should be good for now.
