### ISSUE TITLE
Back-end Monitoring Dashboard

### ISSUE THREAD

**Issue by zeroxjackson** [snl-dev-team/snl-inventory-app#87]
- [x] Set up dashboard to monitor backend and db

- [x] Set up notifications for important events like downtime or crashes

**Comment by isaiahnields** [comment]
![Screen Shot 2020-12-05 at 3 11 26 PM](https://user-images.githubusercontent.com/12752162/101262363-26802680-370c-11eb-9026-2f809ec9816d.png)

See AWS CloudWatch -> Dashboards.
