### ISSUE TITLE
Issue Reporting

### ISSUE THREAD

**Issue by zeroxjackson** [snl-dev-team/snl-inventory-app#88]
- [x] Add ability to one click report bugs or feature recommendations

**Comment by isaiahnields** [comment]
![Uploading Screen Shot 2020-12-05 at 3.00.04 PM.png…]()

**Comment by isaiahnields** [comment]
Clicking on "Report a bug" takes the user to an email template.

**Comment by isaiahnields** [comment]
We can improve this process later if we scale to more users and can't process via email.
