### ISSUE TITLE
Relational Edit Buttons

### ISSUE THREAD

**Issue by zeroxjackson** [snl-dev-team/snl-inventory-app#89]
- [x] New dialog for editing relations

- [x] Edit button on relational cards

**Comment by isaiahnields** [comment]
I managed to solve by adding a few things to the `relational/upsert` dialogs.

**Comment by zeroxjackson** [comment]
@isaiahnields If you had just let me know you didn't want to, I would have done it. You don't have to close issues when the task isn't finished.

**Comment by isaiahnields** [comment]
Task is finished.

**Comment by isaiahnields** [comment]
How is it not complete? We should stick using the same dialog if we can? I made it so that when you click edit it disables the ability to select another one.
