### ISSUE TITLE
Relational Grid Bug

### ISSUE THREAD

**Issue by zeroxjackson** [snl-dev-team/snl-inventory-app#98]
if you enter grid view while in a relational pop up, you will no longer be able update items after exiting the dialog

Video of bug:
https://drive.google.com/file/d/10INfXqmgzqdtusQYlQ9De5bmbMgWfUsu/view?usp=sharing

**Comment by isaiahnields** [comment]
This seems to be due to the fact that we aren't using "/" when we are pushing to history.

**Comment by isaiahnields** [comment]
Fixed.
